
"""
Kuznyechik integral distinguisher and 4-round subkey recovery
without initial key whitening.

This implementation accompanies the paper:

    "Integral Distinguishers and 4-Round Key-Recovery Attack on
     Kuznyechik Without Initial Key Whitening"

Reduced model used in the paper:
    X_0 = P
    X_r = L(S(X_{r-1})) xor K_r,  r >= 1

For the experimental validation, the local reduced-model keys
K_1, ..., K_4 are instantiated by the first four 128-bit subkeys
generated by the standard Kuznyechik key schedule.

The 3-round distinguisher uses the key-independent preimage
    P' = S^{-1}(L^{-1}(x)),
where x ranges over a first-order (A, C^15) structure.

The 4-round recovery first computes
    Y = L^{-1}(C) = S(X_3) xor K'_4,
with
    K'_4 = L^{-1}(K_4),
and tests each byte of K'_4 independently using the balanced
XOR condition over two independent 2^8-element structures.

No external Python packages are required.
"""

import random

# ============================================================
# Kuznyechik S-box and inverse S-box
# ============================================================

SBOX = (
    252, 238, 221, 17, 207, 110, 49, 22, 251, 196, 250, 218, 35, 197, 4, 77,
    233, 119, 240, 219, 147, 46, 153, 186, 23, 54, 241, 187, 20, 205, 95, 193,
    249, 24, 101, 90, 226, 92, 239, 33, 129, 28, 60, 66, 139, 1, 142, 79,
    5, 132, 2, 174, 227, 106, 143, 160, 6, 11, 237, 152, 127, 212, 211, 31,
    235, 52, 44, 81, 234, 200, 72, 171, 242, 42, 104, 162, 253, 58, 206, 204,
    181, 112, 14, 86, 8, 12, 118, 18, 191, 114, 19, 71, 156, 183, 93, 135,
    21, 161, 150, 41, 16, 123, 154, 199, 243, 145, 120, 111, 157, 158, 178, 177,
    50, 117, 25, 61, 255, 53, 138, 126, 109, 84, 198, 128, 195, 189, 13, 87,
    223, 245, 36, 169, 62, 168, 67, 201, 215, 121, 214, 246, 124, 34, 185, 3,
    224, 15, 236, 222, 122, 148, 176, 188, 220, 232, 40, 80, 78, 51, 10, 74,
    167, 151, 96, 115, 30, 0, 98, 68, 26, 184, 56, 130, 100, 159, 38, 65,
    173, 69, 70, 146, 39, 94, 85, 47, 140, 163, 165, 125, 105, 213, 149, 59,
    7, 88, 179, 64, 134, 172, 29, 247, 48, 55, 107, 228, 136, 217, 231, 137,
    225, 27, 131, 73, 76, 63, 248, 254, 141, 83, 170, 144, 202, 216, 133, 97,
    32, 113, 103, 164, 45, 43, 9, 91, 203, 155, 37, 208, 190, 229, 108, 82,
    89, 166, 116, 210, 230, 244, 180, 192, 209, 102, 175, 194, 57, 75, 99, 182,
)

INV_SBOX = [0] * 256
for i, value in enumerate(SBOX):
    INV_SBOX[value] = i


# ============================================================
# GF(2^8) arithmetic
# p(x) = x^8 + x^7 + x^6 + x + 1
# lower byte of the reduction polynomial = 0xC3
# ============================================================

RED_POLY = 0xC3


def gf_mul(a: int, b: int) -> int:
    """Multiply two bytes in GF(2^8) with Kuznyechik's polynomial."""
    a &= 0xFF
    b &= 0xFF
    result = 0

    for _ in range(8):
        if b & 1:
            result ^= a

        carry = a & 0x80
        a = (a << 1) & 0xFF
        if carry:
            a ^= RED_POLY

        b >>= 1

    return result & 0xFF


# ============================================================
# Linear layer L = R^16
# ============================================================

R_COEFFS = (
    148, 32, 133, 16, 194, 192, 1, 251,
    1, 192, 194, 16, 133, 32, 148, 1,
)


def R(state):
    """One Kuznyechik R transformation."""
    acc = state[15]
    for j in range(15):
        acc ^= gf_mul(R_COEFFS[j], state[j])
    return [acc] + state[:15]


def R_inv(state):
    """Inverse of one Kuznyechik R transformation."""
    previous_0_to_14 = state[1:]
    previous_15 = state[0]

    for j in range(15):
        previous_15 ^= gf_mul(R_COEFFS[j], previous_0_to_14[j])

    return previous_0_to_14 + [previous_15]


def L(state):
    """Kuznyechik linear transformation L = R^16."""
    out = state[:]
    for _ in range(16):
        out = R(out)
    return out


def L_inv(state):
    """Inverse Kuznyechik linear transformation."""
    out = state[:]
    for _ in range(16):
        out = R_inv(out)
    return out


# ============================================================
# Standard Kuznyechik key schedule
# ============================================================

REFERENCE_MASTER_KEY = (
    0x8899aabbccddeeff0011223344556677
    << 128
) | 0xfedcba98765432100123456789abcdef

EXPECTED_K4_PRIME_HEX = "e60fce12efb4465985875cbea0201d6e"


def int_to_block(value):
    return [(value >> ((15 - i) * 8)) & 0xFF for i in range(16)]


def block_to_hex(block):
    return "".join(f"{b:02x}" for b in block)


def xor16(a, b):
    return [x ^ y for x, y in zip(a, b)]


def F_function(a1, a0, constant):
    temp = xor16(a1, constant)
    temp = [SBOX[b] for b in temp]
    temp = L(temp)
    return xor16(temp, a0), a1


def standard_key_expansion(master_key):
    """
    Return the ten 128-bit Kuznyechik subkeys.

    keys[0], ..., keys[9] are the first through tenth
    subkeys generated by the standard key schedule.
    """
    high = master_key >> 128
    low = master_key & ((1 << 128) - 1)

    k1 = int_to_block(high)
    k2 = int_to_block(low)

    round_keys = [k1, k2]

    constants = [[0] * 16]
    for j in range(1, 33):
        constants.append(L([0] * 15 + [j]))

    a, b = k1[:], k2[:]

    for group in range(4):
        start = 8 * group + 1
        stop = 8 * (group + 1) + 1

        for index in range(start, stop):
            a, b = F_function(a, b, constants[index])

        round_keys.append(a[:])
        round_keys.append(b[:])

    return round_keys


# ============================================================
# Reduced-round model from the paper
#
# X_0 = P
# X_r = L(S(X_{r-1})) xor K_r
#
# No key is added before the first S-box.
# ============================================================

def encrypt_reduced(plaintext, local_keys):
    """Encrypt with the no-initial-whitening reduced model."""
    state = plaintext[:]

    for key in local_keys:
        state = [SBOX[b] for b in state]
        state = L(state)
        state = xor16(state, key)

    return state


# ============================================================
# 3-round integral distinguisher
#
# X = {(t,c1,...,c15) : t in GF(2^8)}
#
# Paper Eq. (12):
#     P' = { S^{-1}(L^{-1}(x)) : x in X }
#
# IMPORTANT:
# The plaintext preimage is key-independent.  No K_1 is used
# in its construction.
# ============================================================

def generate_first_order_structure(constants):
    """
    Generate a 2^8-element structure of type (A, C^15).

    constants must be a 16-byte list.  Its first entry is ignored
    because byte position 0 is the active byte.
    """
    structure = []

    for t in range(256):
        x = constants[:]
        x[0] = t
        structure.append(x)

    return structure


def preimage_structure(structure):
    """
    Compute the key-independent one-round preimage

        P' = S^{-1}(L^{-1}(X)).

    This is exactly the backward construction used in the paper.
    """
    plaintexts = []

    for x in structure:
        state = L_inv(x)
        state = [INV_SBOX[b] for b in state]
        plaintexts.append(state)

    return plaintexts


def byte_xor_sum(states, position):
    total = 0
    for state in states:
        total ^= state[position]
    return total


def all_bytes_balanced(states):
    """Check the bytewise balanced condition Sigma_i = 0 for all 16 bytes."""
    return all(byte_xor_sum(states, i) == 0 for i in range(16))


def verify_three_round_distinguisher(plaintexts, local_keys):
    """
    Encrypt the key-independent preimage structure for three rounds
    and verify that all sixteen output-byte XOR sums are zero.
    """
    outputs = [encrypt_reduced(p, local_keys[:3]) for p in plaintexts]
    return all_bytes_balanced(outputs)


# ============================================================
# 4-round recovery of K'_4 = L^{-1}(K_4)
#
# Y = L^{-1}(C) = S(X_3) xor K'_4
#
# For byte i and guess g:
#
#     T_i(g) = xor_t S^{-1}(Y_i^(t) xor g)
#
# The correct guess satisfies T_i(g) = 0.
# ============================================================

def candidates_for_structure(ciphertexts):
    """
    Return the candidate list for each byte of K'_4 using one
    2^8-element ciphertext structure.
    """
    transformed = [L_inv(c) for c in ciphertexts]
    candidates = []

    for position in range(16):
        position_candidates = []

        for guess in range(256):
            xor_sum = 0

            for y in transformed:
                xor_sum ^= INV_SBOX[y[position] ^ guess]

            if xor_sum == 0:
                position_candidates.append(guess)

        candidates.append(position_candidates)

    return candidates


def recover_k4_prime(ciphertexts_1, ciphertexts_2):
    """
    Intersect the bytewise candidate sets obtained from two
    independent structures.

    If an intersection contains exactly one element, that byte is
    uniquely recovered.  Otherwise all surviving candidates are
    retained, exactly as stated in the revised Algorithm 1.
    """
    candidates_1 = candidates_for_structure(ciphertexts_1)
    candidates_2 = candidates_for_structure(ciphertexts_2)

    intersections = []
    recovered = []

    for position in range(16):
        common = sorted(set(candidates_1[position]) & set(candidates_2[position]))
        intersections.append(common)

        if len(common) == 1:
            recovered.append(common[0])
        else:
            recovered.append(None)

    return recovered, candidates_1, candidates_2, intersections


# ============================================================
# Reproducibility experiment from the paper
# ============================================================

def main():
    print("=" * 72)
    print("Kuznyechik integral distinguisher and 4-round subkey recovery")
    print("Reduced model without initial key whitening")
    print("=" * 72)

    # The revised paper states that the local keys K1,...,K4 are
    # instantiated by the first four subkeys generated by the
    # standard Kuznyechik key schedule.
    full_schedule = standard_key_expansion(REFERENCE_MASTER_KEY)
    local_keys = full_schedule[:4]

    real_k4_prime = L_inv(local_keys[3])

    print("\nReference master key:")
    print("8899aabbccddeeff0011223344556677")
    print("fedcba98765432100123456789abcdef")

    print("\nLocal reduced-model subkeys:")
    for i, key in enumerate(local_keys, start=1):
        print(f"K{i}  = {block_to_hex(key)}")

    print(f"\nK4' = L^(-1)(K4) = {block_to_hex(real_k4_prime)}")

    # Two independent first-order structures.
    # Fixed seeds make the paper's verification reproducible.
    rng = random.Random(42)
    constants_1 = [rng.randrange(256) for _ in range(16)]
    constants_2 = [rng.randrange(256) for _ in range(16)]

    x_structure_1 = generate_first_order_structure(constants_1)
    x_structure_2 = generate_first_order_structure(constants_2)

    # Paper Eq. (12): P' = S^{-1}(L^{-1}(x)).
    plaintexts_1 = preimage_structure(x_structure_1)
    plaintexts_2 = preimage_structure(x_structure_2)

    # Verify the 3-round distinguisher directly.
    balanced_1 = verify_three_round_distinguisher(plaintexts_1, local_keys)
    balanced_2 = verify_three_round_distinguisher(plaintexts_2, local_keys)

    print("\n3-round distinguisher check:")
    print(f"Structure 1: all 16 output bytes balanced = {balanced_1}")
    print(f"Structure 2: all 16 output bytes balanced = {balanced_2}")

    # Encrypt the two structures for four rounds.
    ciphertexts_1 = [encrypt_reduced(p, local_keys) for p in plaintexts_1]
    ciphertexts_2 = [encrypt_reduced(p, local_keys) for p in plaintexts_2]

    recovered, candidates_1, candidates_2, intersections = recover_k4_prime(
        ciphertexts_1, ciphertexts_2
    )

    print("\nBytewise candidate counts:")
    print("pos : after structure 1 -> after structure 2 -> intersection")

    for i in range(16):
        print(
            f"{i:2d}  : "
            f"{len(candidates_1[i]):3d} -> "
            f"{len(candidates_2[i]):3d} -> "
            f"{len(intersections[i]):3d}"
        )

    unique = all(byte is not None for byte in recovered)

    if unique:
        recovered_hex = block_to_hex(recovered)
        recovered_k4 = L(recovered)

        print("\nRecovered transformed last subkey:")
        print(f"K4' = {recovered_hex}")

        print("\nRecovered local last subkey:")
        print(f"K4  = {block_to_hex(recovered_k4)}")

        print("\nVerification:")
        print(f"All 16 bytes uniquely recovered : {recovered == real_k4_prime}")
        print(
            "Matches value reported in paper: "
            f"{recovered_hex == EXPECTED_K4_PRIME_HEX}"
        )

        if recovered != real_k4_prime:
            raise RuntimeError("Recovered K4' does not match the real transformed subkey.")

        if recovered_hex != EXPECTED_K4_PRIME_HEX:
            raise RuntimeError("Recovered K4' does not match the value reported in the paper.")

    else:
        print("\nAt least one byte has multiple surviving candidates.")
        print("A further independent structure can be used for additional filtering.")

    print("\nData used:")
    print("2 independent structures x 2^8 plaintexts = 2^9 chosen plaintexts")
    print("=" * 72)


if __name__ == "__main__":
    main()
